spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka-app:8761/eureka/
server:
  port: 9090

zuul:
  routes:
    heroservice:
      path: /heroservice/**
      url: http://heroservice:9000/
    helloservice:
      path: /helloservice/**
      url: http://helloservice:8000/
management:
  endpoints:
    web:
      exposure:
        include: '*'
