spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://172.30.48.195:8761/eureka/
server:
  port: 9090

zuul:
  routes:
    helloservice:
      serviceId: helloservice
      path: /helloservice/**
      url: http://helloservice:8000/
management:
  endpoints:
    web:
      exposure:
        include: '*'
